add_subdirectory( slab_recon )
add_subdirectory( Spheromak_tilt )
add_subdirectory( Spheromak_heating )
add_subdirectory( nsf )
add_subdirectory(equilibrium)
add_subdirectory(gs)
add_subdirectory(blanket)
add_subdirectory(paper_1)
add_subdirectory(paper_2)
add_subdirectory(paper_3)
add_subdirectory(hartmann)
add_subdirectory(taylor_flow)
add_subdirectory(ARC)