install(FILES oft_gs.in DESTINATION examples/MUG/equilibrium COMPONENT examples)
configure_file( oft_gs.in ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES tokamaker_f.prof DESTINATION examples/MUG/equilibrium COMPONENT examples)
configure_file( tokamaker_f.prof ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES tokamaker_p.prof DESTINATION examples/MUG/equilibrium COMPONENT examples)
configure_file( tokamaker_p.prof ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES fnsf_eq.h5 DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(fnsf_eq.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES fnsf_pert.h5 DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(fnsf_pert.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES fnsf_eq_115.h5 DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(fnsf_eq_115.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES fnsf_pert_115.h5 DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(fnsf_pert_115.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES fnsf_eq_116.h5 DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(fnsf_eq_116.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES fnsf_pert_116.h5 DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(fnsf_pert_116.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES fnsf_eq_1204.h5 DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(fnsf_eq_1204.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES fnsf_pert_1204.h5 DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(fnsf_pert_1204.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
oft_add_exe(blanket_driver.F90 )
oft_add_exe(blanket_driver_F.F90 )
