install(FILES oft_gs.in DESTINATION examples/MUG/equilibrium COMPONENT examples)
configure_file( oft_gs.in ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES tokamaker_f.prof DESTINATION examples/MUG/equilibrium COMPONENT examples)
configure_file( tokamaker_f.prof ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES tokamaker_p.prof DESTINATION examples/MUG/equilibrium COMPONENT examples)
configure_file( tokamaker_p.prof ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES paper_eq_0115.h5 DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(paper_eq_0115.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES paper_vac_0120.h5 DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(paper_vac_0120.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES paper_plasma_0120.h5 DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(paper_plasma_0120.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES mid_dis.rst DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(mid_dis.rst ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES mid_dis_ins.rst DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(mid_dis_ins.rst ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES psi_plasma_dis.h5 DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(psi_plasma_dis.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES psi_eddy_dis.h5 DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(psi_eddy_dis.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES psi_plasma_dis_ins.h5 DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(psi_plasma_dis_ins.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES psi_eddy_dis_ins.h5 DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(psi_eddy_dis_ins.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
oft_add_exe(driver_dis_p1.F90 )
oft_add_exe(driver_dis_p1_ins.F90 )
oft_add_exe(driver_dis_p2.F90 )
oft_add_exe(driver_dis_p2_ins.F90 )
oft_add_exe(driver_dis_v2.F90 )