install(FILES oft_gs.in DESTINATION examples/MUG/equilibrium COMPONENT examples)
configure_file( oft_gs.in ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES tokamaker_f.prof DESTINATION examples/MUG/equilibrium COMPONENT examples)
configure_file( tokamaker_f.prof ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES tokamaker_p.prof DESTINATION examples/MUG/equilibrium COMPONENT examples)
configure_file( tokamaker_p.prof ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
install(FILES paper_eq_0115.h5 DESTINATION examples/MUG/tDiff COMPONENT examples)
configure_file(paper_eq_0115.h5 ${CMAKE_CURRENT_BINARY_DIR} COPYONLY)
oft_add_exe(driver_ins.F90 )
